<h1 class="mainHeader">Browse Tracks</h1>

<div class="clearFull"></div>

<div class="browseTrackList">
	<div class="content">
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
		</div>
	</div>
</div>



<div class="browseTrackList">
	<div class="content">
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
		</div>
	</div>
</div>

<div class="browseTrackList">
	<div class="content">
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
			<div class="darkDivider"></div>
		</div>
		
		<div class="newTrack">
			<h4>Some Song Title Here</h4>
			<img src="images/albumImage1.jpg" alt="New Album Cover" class="albumCoverImage" />
			<p class="albumText">Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>												
			<div class="newMusicButton"><a href="#">3:30 min | Play</a></div>
			<div class="clear"></div>
		</div>
	</div>
</div>

<div class="clear"></div>
<div class="lightDivider"></div>

<ul class="pagination">
	<li class="txt">More tracks...</li>
	<li><a href="#">1</a></li>
	<li class="current">2</li>
	<li><a href="#">3</a></li>
	<li><a href="#">4</a></li>
	<li><a href="#">6</a></li>
	<li><a href="#">7</a></li>
	<li><a href="#">8</a></li>
	<li><a href="#">9</a></li>
	<li><a href="#">10</a></li>
	<li><a href="#">last</a></li>
</ul>
<div class="clear"></div>
