<h1 class="mainHeader">Browse Tracks</h1>

<div class="clearFull"></div>

<div style="color: margin-top: 10px; padding: 5px; background: #e5e6df; -moz-border-radius: 8px;">
	<form method="get" action="<?php echo $this->url('browse/index'); ?>">
		<input type="text" name="q" style="width: 85%; border: 1px solid black; padding: 3px; font-size: 16px; color: #436757">
		<input type="submit" value="Search">
	</form>
	
	
	
	
</div>