<h1 class="mainHeader"><?php echo $this->safe($track->getName()); ?></h1>

<div class="clearFull"></div>

<div class="contentBox">
	<div id="mp3-player"></div>
	<script type="text/javascript">
		 var so = new SWFObject("<?php echo DIR_FLASH . 'mp3-player.swf'; ?>", "mp3-player", "192", "67", "7", "#000");
		 so.addVariable("autoPlay", "no");
		 so.addVariable("soundPath", "<?php echo $this->url('track/stream', $track->id()); ?>");
		 so.write("mp3-player");
	</script>
	
	<div class="clearFull"></div>
	
	<div class="description">
		<?php echo nl2br($this->safe($track->getDescription())); ?>
	</div>
</div>