<h1 class="mainHeader"><?php echo $this->safe($track->getName()); ?></h1>

<div class="clearFull"></div>

<div class="contentBox">
	<div class="trackLeft">
		<div class="mainImage">
			<a href="<?php echo $this->url('image/viewfullsize', $track->getImageId()); ?>" rel="prettyPhoto">
				<?php echo $this->img($this->url('image/viewlarge', $track->getImageId())); ?>
			</a>
			
			<?php if ( true === $can_favorite ): ?>
				<div class="followBox marginCenter">
					<a href="<?php echo $this->url('track/addtofavorites', $track->id()); ?>"><?php echo Language::__('track_add_to_favorites'); ?></a>
				</div>
			<?php endif; ?>
		</div>
		
		<div class="mp3Player">
			<div id="mp3-player"></div>
			<div class="viewCount">
				<?php echo number_format($track->getViewCount(), 0, '.', ','); ?>
				<?php echo Language::__('views'); ?>
			</div>
			
			<div class="clearFull"></div>
			
			<script type="text/javascript">
				var so = new SWFObject("<?php echo DIR_FLASH . 'mp3-player.swf'; ?>", "mp3-player", "192", "67", "7", "#00000");
				so.addVariable("autoPlay", "no");
				so.addVariable("soundPath", "<?php echo $this->url('track/stream', $track->id()); ?>");
				so.addVariable("wmode", "transparent");
				so.write("mp3-player");
			</script>
			
			<div class="followerBox marginCenter">
				<?php echo $track->getFavoriteList()->length(); ?>
				<span>favorites</span>
			</div>
			
		</div>
	</div>
	
	<div class="trackRight">
		<div class="trackInfo">
			<div>
				<div class="ownerImage">
					<a href="<?php echo $this->url('profile/view', $owner->id()); ?>">
						<?php echo $this->img($this->url('image/viewthumbnail', $owner->getImageId()), '', 'style="border: 0"'); ?>
					</a>
				</div>
				<div class="ownerNickname">
					<a href="<?php echo $this->url('profile/view', $owner->id()); ?>">
						<?php echo $this->safe($owner->getNickname()); ?>
					</a>
				</div>
			</div>
			
			<div class="clear"></div>
			
			<div><?php echo nl2br($this->safe($track->getDescription())); ?></div>
			
			<div class="lightDivider"></div>
		
			<div>Flash Player</div>
			<?php $flash_player = er('site_root', TuneToUs::getConfigRouter()) . ltrim(DIR_FLASH, DS) . 'mp3-player.swf'; ?>
			<input type="text" readonly onclick="this.select()" value="<?php echo $this->safe('<embed width="192" height="67" flashvars="autoPlay=no&amp;soundPath=' . $this->url('track/stream', $track->id()) . '&amp;wmode=transparent" quality="high" bgcolor="#00000" name="mp3-player" id="mp3-player" src="' . $flash_player . '" type="application/x-shockwave-flash">'); ?>">
			
			<div class="clearFull"></div>
			
			<div>URL</div>
			<input type="text" readonly onclick="this.select()" value="<?php echo $this->safe($this->url('track/play', $track->id())); ?>">
			
			<div class="clearFull"></div>
			
			<div>Forum/BBCode</div>
			<?php $image_dir = trim(DIR_IMAGE, DS); ?>
			<input type="text" readonly onclick="this.select()" value="[url=<?php echo $this->url('track/play', $track->id()); ?>][img]<?php echo $this->url($image_dir, 'image-click-to-play-thumbnail.jpg'); ?>[/img]">
		</div>
	</div>
	
	<div class="clearFull"></div>
</div>