<div id="footer">
	<div class="lightDivider"></div>

	<ul class="links first">
		<li class="title">Who Are We?</li>
		<li><a href="<?php echo $this->url('page/view', 'about-us'); ?>">About Us</a></li>
		<li><a href="<?php echo $this->url('contact'); ?>">Contact Us / DMCA Request</a></li>
		<li><a href="http://leftnodesoftware.com" target="_blank">A Leftnode Software Production</a></li>
	</ul>

	<ul class="links">
		<li class="title">Member Help</li>
		<li><a href="<?php echo $this->url('account/register'); ?>">Register</a></li>
		<li><a href="<?php echo $this->url('page/view', 'terms'); ?>">Terms</a></li>
		<li><a href="<?php echo $this->url('page/view', 'privacy-policy'); ?>">Privacy Policy</a></li>
	</ul>

	<ul class="links last">
		<li class="title">Be Our Friend</li>
		<li><a href="http://twitter.com/tunetous" target="_blank">Twitter</a></li>
		<li><a href="http://facebook.com/" target="_blank">Facebook</a></li>
		<li><a href="http://tunetous.wordpress.com" target="_blank">Blog</a></li>
	</ul>

	<div class="clear"></div>

	<div id="copyright">
		&copy; Copyright <?php echo date('Y'); ?> TuneTo.us. All Rights Reserved.
	</div>
</div>