<div id="header">
	
	<div id="join">
		<a href="<?php echo $this->url('account/register'); ?>">REGISTER</a> for added benefits
	</div>
	
	<a href="<?php echo $this->url('index'); ?>" class="logo"><h1>TuneTo.us - Free Music, Free MP3 Hosting, Music Hosting</h1></a>
</div>

<div style="margin-top: 40px;">
	<ul class="navigation">
		<li class="first"><a href="<?php echo $this->url('index'); ?>">Home<span>upload your music</span></a></li>
		<li><a href="<?php echo $this->url('account/register'); ?>">Register<span>improved benefits</span></a></li>
		<li><a href="<?php echo $this->url('account/index'); ?>">My Account<span>your music</span></a></li>
		<li><a href="<?php echo $this->url('browse'); ?>">Browse Music<span>your tastes</span></a></li>
		<li class="last"><a href="<?php echo $this->url('contact'); ?>">Contact<span>let us know</span></a></li>
	</ul>
</div>

<div class="clear"></div>
