<div id="header">

	<div class="smallBanner">
		<?php if ( true === $is_logged_in ): ?>
			<?php echo $this->safe($user->getNickname()); ?>, you can <a href="<?php echo $this->url('account/logout'); ?>"><strong>LOGOUT</strong></a>. Don't forget to come back!
		<?php else: ?>
			<a href="<?php echo $this->url('account/login'); ?>"><strong>LOGIN</strong></a> to add your tracks
		<?php endif; ?>
	</div>
	
	<a href="<?php echo $this->url('index'); ?>" class="logo"><h1>TuneTo.us - Free Music, Free MP3 Hosting, Music Hosting</h1></a>
</div>

<div class="navigationShell">
	<ul class="navigation">
		<li class="first"><a href="<?php echo $this->url('index'); ?>">Home<span>view latest tracks</span></a></li>
		
		<?php if ( true === $is_logged_in ): ?>
			<li><a href="<?php echo $this->url('account/dashboard'); ?>">Dashboard<span>your music and friends</span></a></li>
		<?php else: ?>
			<li><a href="<?php echo $this->url('account/register'); ?>">Register<span>add your tracks</span></a></li>
		<?php endif; ?>

		<li class="last"><a href="<?php echo $this->url('contact'); ?>">Contact<span>let us know</span></a></li>
	</ul>
</div>

<div class="clear"></div>
