<h1 class="mainHeader">Welcome to TuneTo.us - Social MP3 Hosting</h1>

<div class="clearFull"></div>

<p class="largeText center welcomeText">
	<?php echo Language::__('index_welcome_text'); ?>
</p>

<p class="clearFull"></p>

<h3 class="mainHeader"><?php echo Language::__('index_latest_tracks'); ?></h3>
<div class="trackList">
	<?php foreach ( $track_iterator as $track ): ?>
		<?php $id = 'mp3-mini-player-' . $track->id(); ?>
		
		<div class="trackListItemLarge">
			<?php $track_name = $track->getName(); ?>
			<?php if ( strlen($track_name) > 20 ): ?>
				<?php $track_name = substr($track_name, 0, 20) . '...'; ?>
			<?php endif; ?>
			
			<h4><a href="<?php echo $this->url('track/play', $track->id()); ?>"><?php echo $this->safe($track_name); ?></a></h4>
			<div class="image">
				<a href="<?php echo $this->url('track/play', $track->id()); ?>">
					<?php echo $this->img($this->url('image/viewthumbnail', $track->getImageId())); ?>
				</a>
			</div>
			
			<div id="<?php echo $id; ?>" class="center">
				<script type="text/javascript">
					var so = new SWFObject("<?php echo DIR_FLASH . 'mp3-mini-player.swf'; ?>", "<?php echo $id; ?>", "75", "30", "7", "#E5E6DF");
					so.addVariable('autoPlay', 'no');
					so.addVariable('soundPath', '<?php echo $this->url('track/stream', $track->id()); ?>');
					so.addVariable('playerSkin', '6');
					so.write("<?php echo $id; ?>");
				</script>
			</div>
			
		</div>
	<?php endforeach; ?>
</div>

<div class="clear"></div>
