<div class="contentBox">

	<div class="dashboardLeft">
		<h2><?php echo $this->safe($user->getNickname()); ?></h2>

		<div class="mainImage">
			<div class="dashboardImage">
				<?php echo $this->img($this->url('image/viewlarge', $user->getImageId())); ?>
			</div>
			
			<form method="post" action="<?php echo $this->url('account/updatephoto'); ?>" enctype="multipart/form-data" class="center">
				<label>
					<input type="file" name="image" size="20" style="font-size: 10px;">
					<input type="hidden" name="token" value="<?php echo TuneToUs::getToken(); ?>">
					<input type="submit" value="Update Photo" style="font-size: 10px">
				</label>
			</form>
		</div>
		
		<div class="followerCounts">
			<div class="followerBox">
				<?php echo $user->getFollowerList()->length(); ?>
				<span><a href="<?php echo $this->url('account/followers'); ?>">followers</a></span>
			</div>

			<div class="followerBox">
				<?php echo $user->getFollowingList()->length(); ?>
				<span><a href="<?php echo $this->url('account/following'); ?>">following</a></span>
			</div>
		</div>
		
		<div class="clear"></div>
	</div>
	
	<div class="dashboardRight">
		<h2>Your Last 10 Tracks</h2>
		
		<div class="trackList">
			<?php $track_iterator_length = $track_iterator->length(); ?>
			<?php if ( $track_iterator_length > 0 ): ?>
				<?php $i = 1; ?>
				<?php foreach ( $track_iterator as $track ): ?>
					<?php $id = 'mp3-mini-player-' . $track->id(); ?>
					<?php $track_name = $track->getName(); ?>
					<?php $status = $track->getStatus(); ?>
					
					<div class="trackListItem">
						<?php if ( true === $track->canPlay() ): ?>
							<h5><a href="<?php echo $this->url('track/play', $track->id()); ?>"><?php echo $this->safe($track_name); ?></a></h5>
						<?php else: ?>
							<h5><?php echo $this->safe($track_name); ?></h5>
						<?php endif; ?>
						
						<div>
							<?php echo $this->img($this->url('image/viewmicro', $track->getImageId()), '', 'class="image"'); ?>
							<div id="<?php echo $id; ?>">
								<?php if ( false === $track->canPlay() ): ?>
									<?php echo Language::__('processing_track'); ?>
								<?php else: ?>
									<script type="text/javascript">
										var so = new SWFObject("<?php echo DIR_FLASH . 'mp3-mini-player.swf'; ?>", "<?php echo $id; ?>", "75", "30", "7", "#ffffff");
										so.addVariable('autoPlay', 'no');
										so.addVariable('soundPath', '<?php echo $this->url('track/stream', $track->id()); ?>');
										so.addVariable('playerSkin', '6');
										so.write("<?php echo $id; ?>");
									</script>
								<?php endif; ?>
							</div>
						</div>
					</div>
				<?php endforeach; ?>
			<?php else: ?>
				<p><?php echo Language::__('account_upload_tracks_first'); ?></p>
			<?php endif; ?>
		</div>
		
		<div class="clearFull center">
			<a href="<?php echo $this->url('account/tracklist'); ?>"><?php echo Language::__('account_view_all_tracks'); ?></a>
		</div>
		
	</div>
	
	
</div>