<h1 class="mainHeader">Your Account</h1>

<div class="clearFull"></div>

<div class="accountTrackList">
	<div class="content">
		<h2 class="mainHeader">Your Tracks</h2>
		
		<div class="darkDivider"></div>
		
		<?php $i = 1; ?>
		<?php $length = $track_list->length(); ?>
		<?php if ( $length > 0 ): ?>
			<?php foreach ( $track_list as $track ): ?>
				<?php $safe_name = $this->safe($track->getName()); ?>
				<?php $short_description = substr($track->getDescription(), 0, 128); ?>
				<?php $safe_description = $this->safe($short_description); ?>
				<div class="newTrack">
					<h4><?php echo $safe_name; ?></h4>
					<img src="<?php echo ttu_user_get_gravatar($user->getEmailAddress()); ?>" alt="<?php echo $safe_name; ?>" class="albumCoverImage" />
					<p class="albumText"><?php echo $safe_description; ?></p>
					<div class="newMusicButton"><a href="<?php echo $this->url('track/play', $track->id()); ?>"><?php echo $track->getLength(); ?> <?php echo _('seconds'); ?> | <?php echo _('Play'); ?></a></div>
					<div class="clear"></div>
					<?php if ( $i++ != $length ): ?>
						<div class="darkDivider"></div>
					<?php endif; ?>
				</div>
			<?php endforeach; ?>
		<?php else: ?>
			<p>You have not uploaded any tracks yet! What are you waiting for? Upload one now.</p>
		<?php endif; ?>
	</div>
</div>

<div class="uploadTrack">
	<div class="content">
		<h2 class="mainHeader">Upload Your Track</h2>
		<div class="lightDivider"></div>
		<?php echo $upload_form; ?>
	</div>
</div>