<h1 class="mainHeader"><?php echo $section_title; ?></h1>

<div class="clearFull"></div>

<ul class="accountMenu">
	<li><a href="<?php echo $this->url('account/dashboard'); ?>">Dashboard</a></li>
	<li><a href="<?php echo $this->url('account/upload'); ?>">Upload Track</a></li>
	<li><a href="<?php echo $this->url('account/update'); ?>">Update Profile</a></li>
	<li style="float: right"><a href="<?php echo $this->url('account/profile', $user->id()); ?>">My Public Profile</a></li>
</ul>
	
<div class="clear"></div>

<?php echo $content; ?>

<div class="clear"></div>
