<h1 class="mainHeader"><?php echo $section_title; ?></h1>

<div class="clearFull"></div>

<ul class="accountMenu">
	<li><a href="<?php echo $this->url('account/dashboard'); ?>">Dashboard</a></li>
	<li><a href="<?php echo $this->url('account/upload'); ?>">Upload Track</a></li>
	<li><a href="<?php echo $this->url('account/update'); ?>">Update Settings</a></li>
	<li><a href="<?php echo $this->url('account/tracklist'); ?>">Track List</a></li>
	<li><a href="<?php echo $this->url('account/favoritelist'); ?>">Favorites</a></li>
	<li><a href="<?php echo $this->url('account/privacy'); ?>">Privacy</a></li>
	<li><a href="<?php echo $this->url('account/messagelist'); ?>">Messages</a></li>
</ul>
	
<div class="clear"></div>

<?php echo $content; ?>

<div class="clear"></div>