<?php $nickname = $profile->getNickname(); ?>
<?php $nickname = $this->safe($nickname); ?>

<h1 class="mainHeader"><?php echo sprintf(Language::__('account_profile'), $nickname); ?></h1>

<div class="clearFull"></div>

<div class="contentBox">

	<div class="dashboardLeft">
		<div class="followerBox">
			<?php echo $profile->getFollowerCount(); ?>
			<span>followers</span>
		</div>

		<div class="followerBox">
			<?php echo $profile->getFollowingCount(); ?>
			<span>following</span>
		</div>

		<div class="clearFull"></div>
		
		<div class="dashboardImage">
			<?php echo $this->img($this->url('account/photo', $profile->id(), PHOTO)); ?>
		</div>
		
		<div class="lightDivider"></div>
		
		<?php $biography = $this->safe($profile->getBiography()); ?>
		<?php if ( false === empty($biography) ): ?>
			<h3>Biography</h3>
			<div>
				<?php echo nl2br($biography); ?>
			</div>
			<div class="lightDivider"></div>
		<?php endif; ?>
		
		<?php $interests = $this->safe($profile->getInterests()); ?>
		<?php if ( false === empty($interests) ): ?>
			<h3>Interests</h3>
			<div>
				<?php echo nl2br($interests); ?>
			</div>
			<div class="lightDivider"></div>
		<?php endif; ?>
		
		<?php $music = $this->safe($profile->getMusic()); ?>
		<?php if ( false === empty($music) ): ?>
			<h3>Favorite Music</h3>
			<div>
				<?php echo nl2br($music); ?>
			</div>
			<div class="lightDivider"></div>
		<?php endif; ?>
		
		<?php $movies = $this->safe($profile->getMovies()); ?>
		<?php if ( false === empty($movies) ): ?>
			<h3>Favorite Movies</h3>
			<div>
				<?php echo nl2br($movies); ?>
			</div>
			<div class="lightDivider"></div>
		<?php endif; ?>
		
		<?php $books = $this->safe($profile->getBooks()); ?>
		<?php if ( false === empty($books) ): ?>
			<h3>Favorite Books</h3>
			<div>
				<?php echo nl2br($books); ?>
			</div>
			<div class="lightDivider"></div>
		<?php endif; ?>
		
		
		
		
		<?php if ( true === $can_follow ): ?>
			you can follow this user!
		<?php endif; ?>
	</div>
	
	<div class="dashboardRight">
		<h2>Last 10 Tracks</h2>
		
		<?php $track_iterator_length = $track_iterator->length(); ?>
		<?php if ( $track_iterator_length > 0 ): ?>
			<?php $i = 1; ?>
			<?php foreach ( $track_iterator as $track ): ?>
				<div>
					<?php $track_name = $track->getName(); ?>
					<h4><a href="<?php echo $this->url('track/play', $track->id()); ?>"><?php echo $this->safe($track_name); ?></a></h4>
					<div class="trackData">
						<a href="<?php echo $this->url('track/play', $track->id()); ?>">
							<?php echo $track->getFormattedLength(); ?> | <?php echo Language::__('play'); ?>
						</a>
					</div>
				</div>
				<?php if ( $i++ != $track_iterator_length ): ?>
					<div class="lightDivider"></div>
				<?php endif; ?>
			<?php endforeach; ?>
		<?php else: ?>
			<p><?php echo Language::__('account_upload_tracks_first'); ?></p>
		<?php endif; ?>
	</div>
</div>