<h1 class="mainHeader">Register For An Account</h1>

<div class="clearFull"></div>

<div class="accountRegister">
	<form method="post" action="<?php echo $this->url('account/register'); ?>">
		<p>
			Registration is entirely free, and allows you to manage your uploads,
			favorite other uploads, and see basic statistics. After you register,
			you can upgrade your account to provide more uploads, larger uploads,
			and to see more statistics on your files.
		</p>
		
		<label>
			<span class="req">Nick Name <em class="expl">(you'll login with this)</em></span>
			<input type="text" name="register[nickname]" value="<?php echo $this->safe(er('nickname', $register)); ?>" class="text">
			<div class="error"><?php echo $this->error('nickname'); ?></div>
		</label>
		
		
		<label>
			<span class="req">Email Address <em class="expl">(for official contacts)</em></span>
			<input type="text" name="register[email_address]" value="<?php echo $this->safe(er('email_address', $register)); ?>" class="text">
			<div class="error"><?php echo $this->error('email_address'); ?></div>
		</label>
	
		<label>
			<span class="req">Passsword <em class="expl">(make this 6 characters or more, and secure)</em></span>
			<input type="password" name="register[password]" value="<?php echo $this->safe(er('password', $register)); ?>" class="text">
			<div class="error"><?php echo $this->error('password'); ?></div>
		</label>
	
		<label>
			<span>Your Name <em class="expl">(can be your real name, fake name, alias, or AKA)</em></span>
			<input type="text" name="register[name]" value="<?php echo $this->safe(er('name', $register)); ?>" class="text">
			<div class="error"><?php echo $this->error('name'); ?></div>
		</label>

		<label>
			<?php $gender = er('gender', $register); ?>
			<span>Gender</span>
			<select name="register[gender]">
				<option value="<?php echo GENDER_MALE; ?>" <?php echo ( GENDER_MALE == $gender ? 'selected' : NULL ); ?>>Male</option>
				<option value="<?php echo GENDER_FEMALE; ?>" <?php echo ( GENDER_FEMALE == $gender ? 'selected' : NULL ); ?>>Female</option>
			</select>
			<div class="error"><?php echo $this->error('gender'); ?></div>
		</label>
		
		
		
		<p><strong>Bold fields are required.</strong></p>
		
		<input type="hidden" name="token" value="<?php echo TTU::getToken(); ?>">
		<input type="submit" class="submitButton" value="Register">
	</form>
</div>