<form method="post" action="<?php echo $this->url('account/register'); ?>">
	<label>
		<span class="req">Email Address</span>
		<input type="text" name="register[email_address]" class="smallText">
	</label>

	<label>
		<span class="req">Passsword</span>
		<input type="password" name="register[password]" class="smallText">
	</label>

	<label>
		<span class="req">Nick Name</span>
		<input type="text" name="register[nickname]" class="smallText">
	</label>

	<p style="font-size: 11px;"><strong>Bold fields are required.</strong></p>

	<input type="hidden" name="token" value="<?php echo API::getToken(); ?>">
	<input type="submit" class="formButton" value="Register">
</form>