<div class="accountDashboard">	
	<p><strong>Bold fields are required.</strong></p>
	
	<form method="post" action="<?php echo $this->url('account/update'); ?>" enctype="multipart/form-data">
		<label>
			<span class="req">Email Address</span>
			<input type="text" name="user[email_address]" value="<?php echo $this->safe(er('email_address', $user)); ?>" class="text">
			<div class="error"><?php echo $this->error('email_address'); ?></div>
		</label>
	
		<label>
			<span class="req">Your Name</span>
			<input type="text" name="user[name]" value="<?php echo $this->safe(er('name', $user)); ?>" class="text">
			<div class="error"><?php echo $this->error('name'); ?></div>
		</label>
	
		<label>
			<span class="req">Your Name</span>
			<input type="text" name="user[name]" value="<?php echo $this->safe(er('name', $user)); ?>" class="text">
			<div class="error"><?php echo $this->error('name'); ?></div>
		</label>
	
		<label>
			<span>Gender</span>
			<select name="user[gender]">
				<option value="male">Male</option>
				<option value="female">Female</option>
			</select>
			<div class="error"><?php echo $this->error('gender'); ?></div>
		</label>
		
		<label>
			<span>Country</span>
			<input type="text" name="user[country]" value="<?php echo $this->safe(er('country', $user)); ?>" class="text">
			<div class="error"><?php echo $this->error('country'); ?></div>
		</label>
		
		<label>
			<span>Biography</span>
			<textarea rows="3" name="user[biography]" class="textLong"><?php echo $this->safe(er('biography', $user)); ?></textarea>
			<div class="error"><?php echo $this->error('biography'); ?></div>
		</label>
		
		<label>
			<span>Interests</span>
			<textarea rows="3" name="user[interests]" class="textLong"><?php echo $this->safe(er('interests', $user)); ?></textarea>
			<div class="error"><?php echo $this->error('interests'); ?></div>
		</label>
		
		<label>
			<span>Favorite Music</span>
			<textarea rows="3" name="user[music]" class="textLong"><?php echo $this->safe(er('music', $user)); ?></textarea>
			<div class="error"><?php echo $this->error('music'); ?></div>
		</label>
		
		<label>
			<span>Favorite Movies</span>
			<textarea rows="3" name="user[movies]" class="textLong"><?php echo $this->safe(er('movies', $user)); ?></textarea>
			<div class="error"><?php echo $this->error('movies'); ?></div>
		</label>
		
		<label>
			<span>Favorite Books</span>
			<textarea rows="3" name="user[books]" class="textLong"><?php echo $this->safe(er('books', $user)); ?></textarea>
			<div class="error"><?php echo $this->error('books'); ?></div>
		</label>
		
		<label>
			<span>Your Website</span>
			<input type="text" name="user[website1]" value="<?php echo $this->safe(er('website1', $user)); ?>" class="text">
			<div class="error"><?php echo $this->error('website1'); ?></div>
		</label>
		
		<label>
			<span>Your Photo</span>
			<input type="file" name="photo" ></textarea>
			<div class="error"><?php echo $this->error('photo'); ?></div>
		</label>
		
		<input type="hidden" name="token" value="<?php echo TTU::getToken(); ?>">
		<input type="submit" class="submitButton" value="Update Profile">
	</form>
</div>