<div class="accountDashboard">	
	<p><strong>Bold fields are required.</strong></p>
	
	<form method="post" action="<?php echo $this->url('track/upload'); ?>" enctype="multipart/form-data">
		<label>
			<span class="req">Your MP3 File</span>
			<input type="file" name="track">
			<div class="error"><?php echo $this->error('track'); ?></div>
		</label>
		
		<label>
			<span>Associated Image <em class="expl">(your profile photo will be used for this track unless you upload an image)</em></span>
			<input type="file" name="image">
			<div class="error"><?php echo $this->error('image'); ?></div>
		</label>
		
		<label>
			<span class="req">Track Name</span>
			<input type="text" name="track[name]" value="<?php echo $this->safe(er('name', $track)); ?>" class="text">
			<div class="error"><?php echo $this->error('name'); ?></div>
		</label>
		
		<label>
			<span class="req">Description</span>
			<textarea rows="3" name="track[description]" class="textLong"><?php echo $this->safe(er('description', $track)); ?></textarea>
			<div class="error"><?php echo $this->error('description'); ?></div>
		</label>
		
		<p>
			By uploading this file, you agree to our <a href="<?php echo $this->url('page/view', 'terms'); ?>">Terms of Agreement</a> and assert you are the copyright owner of this file.
		</p>
		
		<input type="hidden" name="token" value="<?php echo TTU::getToken(); ?>">
		<input type="submit" class="submitButton" value="Upload Track">
	</form>

</div>